name: hs_database_repository
description: Hitspot package to manage database utilities
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  cloud_firestore: ^4.11.0
  firebase_storage: ^11.7.6
  hs_authentication_repository:
    path: ../hs_authentication_repository
  geoflutterfire2: ^2.3.15
  image: ^3.0.1
  firebase_storage: ^11.7.4
  path_provider: ^2.1.3
  path: ^1.9.0
