name: hs_search_repository
description: Hitspot package to manage searching
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  shared_preferences: ^2.2.3
  algolia_helper_flutter: ^1.0.0
  infinite_scroll_pagination: ^3.2.0
  flutter_config: ^2.0.2
  hs_authentication_repository:
    path: ../hs_authentication_repository

flutter:
  assets:
    - ../../.env