name: hitspot
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.5+1

environment:
  sdk: '>=3.4.3 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  app_settings: ^5.1.1
  auto_size_text: ^3.0.0
  avatar_stack: ^1.2.0
  badges: ^3.1.2
  badword_guard: ^1.0.1
  bloc: ^8.1.4
  cached_network_image: ^3.3.1
  choice: ^2.3.2
  connectivity_plus: ^6.0.3
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  exif: ^3.3.0
  expandable_bottom_sheet: ^1.1.1+1
  extended_nested_scroll_view: ^6.2.1
  firebase_core: ^3.3.0
  firebase_messaging: ^15.0.4
  flex_color_picker: ^3.4.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_image: ^0.0.6+1
  flutter_native_splash: ^2.4.0
  flutter_slidable: ^3.1.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  formz: ^0.7.0
  gap: ^3.0.1
  go_router: ^14.1.4
  google_fonts: ^6.2.1
  hs_authentication_repository:
    path: packages/hs_authentication_repository
  hs_database_repository:
    path: packages/hs_database_repository
  hs_debug_logger:
    path: packages/hs_debug_logger
  hs_location_repository:
    path: packages/hs_location_repository
  hs_storage_repository:
    path: packages/hs_storage_repository
  hs_theme_repository:
    path: packages/hs_theme_repository
  hs_toasts:
    path: packages/hs_toasts
  image_cropper: ^7.0.5
  image_picker: ^1.1.2
  intl: ^0.19.0
  loading_animation_widget: ^1.2.1
  lottie: ^3.1.2
  melos: ^6.1.0
  modal_bottom_sheet: ^3.0.0
  newton_particles: ^0.1.8
  page_transition: ^2.1.0
  pair: ^0.1.2
  permission_handler: ^11.3.1
  photo_view: ^0.15.0
  profanity_filter: ^2.0.0
  rename: ^3.0.2
  reorderable_grid: ^1.0.10
  settings_ui: ^2.0.2
  share_plus: ^9.0.0
  shimmer: ^3.0.0
  supabase_flutter: ^2.5.4
  upgrader: ^10.3.0
  url_launcher: ^6.1.10
  uuid: ^4.4.2
  zoom_pinch_overlay: ^1.4.3

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # General
    - assets/
    # Logos
    - assets/icons/logo/
    - assets/icons/logotype/
    # Configuration
    - .env
    # Splash Screen
    - assets/splash/
    # Map
    - assets/map/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
