name: hs_spot_model
description: Hitspot package that contains spot model
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter_geo_hash: ^0.0.4
  hs_authentication_repository:
    path: ../hs_authentication_repository
  geoflutterfire2: ^2.3.15
  path: ^1.9.0
  