// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class HSDevelopmentFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1QzZdI3hvC9uAmmKxeu9YKHpJYJ8vcIA',
    appId: '1:145078839676:web:7c1b702562417f27135cf9',
    messagingSenderId: '145078839676',
    projectId: 'hitspot-2092c',
    authDomain: 'hitspot-2092c.firebaseapp.com',
    storageBucket: 'hitspot-2092c.appspot.com',
    measurementId: 'G-9SM7T0ZV2L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmfr06x8ufZJg8rJZdJtTpEgZXJszJI1M',
    appId: '1:145078839676:android:66659f5c349007e9135cf9',
    messagingSenderId: '145078839676',
    projectId: 'hitspot-2092c',
    storageBucket: 'hitspot-2092c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0m8arsy9yiRXYdPZ0N93IcBm1fwKAvw0',
    appId: '1:145078839676:ios:076f35fc958880e6135cf9',
    messagingSenderId: '145078839676',
    projectId: 'hitspot-2092c',
    storageBucket: 'hitspot-2092c.appspot.com',
    androidClientId:
        '145078839676-091d679srcjfn3ukip6jhtlv4ol2o3te.apps.googleusercontent.com',
    iosBundleId: 'hitspot.hitspot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0m8arsy9yiRXYdPZ0N93IcBm1fwKAvw0',
    appId: '1:145078839676:ios:31c84017e11face5135cf9',
    messagingSenderId: '145078839676',
    projectId: 'hitspot-2092c',
    storageBucket: 'hitspot-2092c.appspot.com',
    androidClientId:
        '145078839676-091d679srcjfn3ukip6jhtlv4ol2o3te.apps.googleusercontent.com',
    iosBundleId: 'com.example.hitspot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1QzZdI3hvC9uAmmKxeu9YKHpJYJ8vcIA',
    appId: '1:145078839676:web:097ca221a3c8bff2135cf9',
    messagingSenderId: '145078839676',
    projectId: 'hitspot-2092c',
    authDomain: 'hitspot-2092c.firebaseapp.com',
    storageBucket: 'hitspot-2092c.appspot.com',
    measurementId: 'G-R2V2GYG0N1',
  );
}
