name: hs_storage_repository
description: Hitspot package to manage storage utilities
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  supabase_flutter: ^2.5.4
  hs_debug_logger:
    path: ../hs_debug_logger
  flutter_native_image: ^0.0.6+1
  pair: ^0.1.2

