name: hs_location_repository
description: Hitspot package to manage location utilities
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  geolocator: ^12.0.0
  geocoding: ^3.0.0
