name: hs_toasts
description: Hitspot package to handle displaying popups and toasts
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  toastification: ^1.2.1
  font_awesome_flutter: ^10.7.0