name: hs_firebase_config
description: Hitspot package to manage Firebase configurations and environments
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  firebase_core: ^2.30.0
  cloud_firestore: ^4.11.0