name: hs_network_repository
description: Hitspot package to manage network utilities
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  http: ^0.13.6
  hs_debug_logger:
    path: ../hs_debug_logger
