name: hs_location_repository
description: Hitspot package to manage location utilities
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  google_places_flutter: ^2.0.8
  google_maps_flutter: ^2.9.0
  uuid: ^4.4.0
  dio: ^5.4.3+1
  dart_geohash: ^2.1.0
  map_launcher: ^3.3.1  
  google_maps_cluster_manager: ^3.1.0
  hs_database_repository:
    path: ../hs_database_repository
  hs_debug_logger:
    path: ../hs_debug_logger
  url_launcher: ^6.3.0
  pair: ^0.1.2
  supabase: ^2.5.0
