name: hs_mailing_repository
description: Hitspot package to manage sending emails
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  dio: ^5.4.3+1
  flutter_dotenv: ^5.1.0

flutter:
  assets:
    - ../../.env